### ISSUE TITLE
Docker starts and restarts

### ISSUE THREAD

**Issue by JuniorGamingTime** [DomiStyle/docker-idrac6#48]
So im having an issue with the idrac docker boot looping. i get an error in the logs saying:
`Failed to download avctKVM.jar, please check your settings`

In the Web Gui the screen goes black and then just shuts off with the error "1006" just like in #34 

docker compose:

```
version: '3.1'

services:
  idrac1:
    image: domistyle/idrac6
    restart: always
    ports:
      - 5800:5800
      - 5900:5900
    environment:
      - IDRAC_HOST=10.xx.xx.xx
      - IDRAC_USER=user
      - IDRAC_PASSWORD=12345678
    volumes:
      - /Automation/iDrac/app:/app
      - /Automation/iDrac/media:/vmedia
      - /Automation/iDrac/screenshots:/screenshots
```
