### ISSUE TITLE
idrac6 avctKVM issue

### ISSUE THREAD

**Issue by bullfrog-au** [DomiStyle/docker-idrac6#78]
Appears similar to [Issue with downloading avctKVM](https://github.com/DomiStyle/docker-idrac6/issues/1).

T610 currently running iDRAC6 (Firmware 2.92 build 05)

Docker compose file is
```
version: '3.1'

services:
  idrac1:
    image: domistyle/idrac6
    restart: always
    ports:
      - 5800:5800
      - 5900:5900
    environment:
      - IDRAC_HOST=192.168.1.135
      - IDRAC_USER=root
      - IDRAC_PASSWORD=calvin
    # Experimental! To directly mount an iso as iDRAC virtual media, 
    # uncomment the below and set to a filename that appears in /vmedia
      # - VIRTUAL_ISO=name_of_iso.iso
    volumes:
      - /path/to/app:/app
      - /path/to/media:/vmedia
      - /path/to/screenshots:/screenshots
#  idrac2:
#    image: domistyle/idrac6
#    restart: always
#    ports:
#      - 5801:5800
#      - 5901:5900
#    secrets:
#      - idrac_host
#      - idrac_user
#      - idrac_password
#    volumes:
#      - /path/to/app:/app
#      - /path/to/media:/vmedia
#      - /path/to/screenshots:/screenshots
#secrets:
#  idrac_host:
#    file: ./idrac_host.txt
#  idrac_user:
#    file: ./idrac_user.txt
#  idrac_password:
#    file: ./idrac_password.txt
```

When this is run, the container fails with the below error,

```
idrac1-1  | Connecting to 192.168.1.135:443... connected.
idrac1-1  | WARNING: The certificate of '192.168.1.135' is not trusted.
idrac1-1  | WARNING: The certificate of '192.168.1.135' doesn't have a known issuer.
idrac1-1  | WARNING: The certificate of '192.168.1.135' has expired.
idrac1-1  | The certificate has expired
idrac1-1  | The certificate's owner does not match hostname '192.168.1.135'
idrac1-1  | HTTP request sent, awaiting response... 200 OK
idrac1-1  | Length: 1006154 (983K) [application/octet-stream]
idrac1-1  | avctKVM.jar: Permission denied
idrac1-1  | 
idrac1-1  | Cannot write to 'avctKVM.jar' (Permission denied).
idrac1-1  | Failed to download avctKVM.jar, please check your settings
idrac1-1  | [services.d] stopping services
idrac1-1  | [services.d] stopping app...
idrac1-1  | [services.d] stopping logmonitor...
idrac1-1  | [services.d] stopping openbox...
idrac1-1  | [services.d] stopping x11vnc...
idrac1-1  | caught signal: 15
idrac1-1  | 20/03/2025 10:28:00 deleted 26 tile_row polling images.
idrac1-1  | [services.d] stopping statusmonitor...
idrac1-1  | [services.d] stopping xvfb...
idrac1-1  | [services.d] stopping certsmonitor...
idrac1-1  | [services.d] stopping nginx...
idrac1-1  | [services.d] stopping s6-fdholderd...
idrac1-1  | [cont-finish.d] executing container finish scripts...
idrac1-1  | [cont-finish.d] done.
idrac1-1  | [s6-finish] syncing disks.
idrac1-1  | [s6-finish] sending all processes the TERM signal.
idrac1-1  | [s6-finish] sending all processes the KILL signal and exiting.
idrac1-1 exited with code 2
```

I am able to manually download the .jnlp file from "https://192.168.1.135/software/avctKVM.jar" which returns
```
<?xml version="1.0" encoding="UTF-8"?>
<jnlp codebase="https://192.168.1.135:443" spec="1.0+">
<information>
  <title>iDRAC6 Virtual Console Client</title>
  <vendor>Dell Inc.</vendor>
   <icon href="https://192.168.1.135:443/images/logo.gif" kind="splash"/>
   <shortcut online="true"/>
 </information>
 <application-desc main-class="com.avocent.idrac.kvm.Main">
   <argument>ip=192.168.1.135</argument>
   <argument>vmprivilege=true</argument>
   <argument>helpurl=https://192.168.1.135:443/help/contents.html</argument>
   <argument>title=idrac-IGOR%2C+PowerEdge+T610%2C+User%3Aroot</argument>
   <argument>user=1681692777</argument>
   <argument>passwd=1714636915</argument>
   <argument>kmport=5900</argument>
   <argument>vport=5900</argument>
   <argument>apcp=1</argument>
   <argument>version=2</argument>
 </application-desc>
 <security>
   <all-permissions/>
 </security>
 <resources>
   <j2se version="1.6+"/>
   <jar href="https://192.168.1.135:443/software/avctKVM.jar" download="eager" main="true" />
 </resources>
 <resources os="Windows" arch="x86">
   <nativelib href="https://192.168.1.135:443/software/avctKVMIOWin32.jar" download="eager"/>
   <nativelib href="https://192.168.1.135:443/software/avctVMWin32.jar" download="eager"/>
 </resources>
 <resources os="Windows" arch="amd64">
   <nativelib href="https://192.168.1.135:443/software/avctKVMIOWin64.jar" download="eager"/>
   <nativelib href="https://192.168.1.135:443/software/avctVMWin64.jar" download="eager"/>
 </resources>
 <resources os="Windows" arch="x86_64">
   <nativelib href="https://192.168.1.135:443/software/avctKVMIOWin64.jar" download="eager"/>
   <nativelib href="https://192.168.1.135:443/software/avctVMWin64.jar" download="eager"/>
 </resources>
  <resources os="Linux" arch="x86">
    <nativelib href="https://192.168.1.135:443/software/avctKVMIOLinux32.jar" download="eager"/>
   <nativelib href="https://192.168.1.135:443/software/avctVMLinux32.jar" download="eager"/>
  </resources>
  <resources os="Linux" arch="i386">
    <nativelib href="https://192.168.1.135:443/software/avctKVMIOLinux32.jar" download="eager"/>
   <nativelib href="https://192.168.1.135:443/software/avctVMLinux32.jar" download="eager"/>
  </resources>
  <resources os="Linux" arch="i586">
    <nativelib href="https://192.168.1.135:443/software/avctKVMIOLinux32.jar" download="eager"/>
   <nativelib href="https://192.168.1.135:443/software/avctVMLinux32.jar" download="eager"/>
  </resources>
  <resources os="Linux" arch="i686">
    <nativelib href="https://192.168.1.135:443/software/avctKVMIOLinux32.jar" download="eager"/>
   <nativelib href="https://192.168.1.135:443/software/avctVMLinux32.jar" download="eager"/>
  </resources>
  <resources os="Linux" arch="amd64">
    <nativelib href="https://192.168.1.135:443/software/avctKVMIOLinux64.jar" download="eager"/>
   <nativelib href="https://192.168.1.135:443/software/avctVMLinux64.jar" download="eager"/>
  </resources>
  <resources os="Linux" arch="x86_64">
    <nativelib href="https://192.168.1.135:443/software/avctKVMIOLinux64.jar" download="eager"/>
   <nativelib href="https://192.168.1.135:443/software/avctVMLinux64.jar" download="eager"/>
  </resources>
  <resources os="Mac OS X" arch="x86_64">
    <nativelib href="https://192.168.1.135:443/software/avctKVMIOMac64.jar" download="eager"/>
   <nativelib href="https://192.168.1.135:443/software/avctVMMac64.jar" download="eager"/>
  </resources>
</jnlp>
```

From the error message, this looks like a permissions error local to the container to me, but I have no idea how to solve it inside docker.
